### ISSUE TITLE
Validate queries using BQ Dryrun option

### ISSUE THREAD

**Issue by fbertsch** [mozilla/bigquery-etl#253] opened 2019-07-23 14:59 UTC
Tests cover specific cases, but running the query in the correct project with a dryrun can ensure that there are no obvious schema incompatibilities the tests may have missed.

This will require us to define in bigquery-etl which project/dataset the query is supposed to run in, but we could also merge that [with the Airflow runner](https://github.com/mozilla/telemetry-airflow/blob/master/dags/main_summary.py#L392) so it's only described here (rather than in two places).

[There is an example of using this in re:dash.]( https://github.com/mozilla/redash-stmo/blob/master/src/redash_stmo/data_sources/validator/extension.py#L21)

**Comment by jklukas** [comment] 2019-07-23 18:45
>  will require us to define in bigquery-etl which project/dataset the query is supposed to run in

We will be codifying which default dataset is used per query as part of https://github.com/mozilla/bigquery-etl/issues/189

**Comment by relud** [comment] 2019-07-24 08:16
this is a duplicate of #188

**Closed by relud** 2019-07-24 08:16 UTC
