### ISSUE TITLE
Error in publish_views: Unclosed identifier literal at [2:3] in moz-fx-data-shared-prod.glam_etl.org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1

### ISSUE THREAD

**Issue by whd** [mozilla/bigquery-etl#1232] opened 2020-08-18 02:54 UTC
/CC @acmiyaguchi 

It's not immediately obvious to me why this is missing since the source appears to have it: https://github.com/mozilla/bigquery-etl/blob/master/sql/glam_etl/org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1/view.sql, but the query as attempted to publish follows:

```
                                          -----Query Job SQL Follows-----                                          
   1:CREATE OR REPLACE VIEW
   2:  `moz-fx-data-shared-prod.glam_etl.org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1
   3:AS
   4:SELECT
   5:  *
   6:FROM
   7:  `moz-fx-data-shared-prod`.glam_etl.org_mozilla_firefox__view_clients_daily_histogram_aggregates_v1
```

I suspect some issue with replacement logic for e.g. `--target-project` is the cause, though the invocation here failing uses `--target-project moz-fx-data-shared-prod`. I would further guess this has to do with a whole identifier being backticked in some cases but in other cases only the project id is.

**Comment by acmiyaguchi** [comment] 2020-08-18 16:02
The problem is that the view definition is missing a closing back-tick. I didn't run this entire DAG through a testing airflow instance.

Also, I forgot to remove these ETL scripts from `publish_view` script. These are checked into the repository so that there is something to diff against.

**Comment by acmiyaguchi** [comment] 2020-08-18 17:52
Actually, it looks like the view definition is valid, it's just that the sql is invalid due to the way that the datasets are actually set up. We dynamically generate SQL for the real job anyhow.

**Closed** 2020-08-18 18:33 UTC
