### ISSUE TITLE
Add documentation about published UDFs to docs.tmo

### ISSUE THREAD

**Issue by scholtzan** [mozilla/bigquery-etl#249] opened 2019-07-22 22:17 UTC
Factored out from https://github.com/mozilla/bigquery-etl/issues/222. Add documentation to the [Firefox Data Documentation](http://docs-origin.telemetry.mozilla.org/cookbooks/bigquery.html) about published UDFs.

**Comment by tdsmith** [comment] 2019-08-19 23:13
Closing as a dupe of #228.

**Closed by tdsmith** 2019-08-19 23:13 UTC
